events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;

    gzip on;
    gzip_types application/json;
    gzip_comp_level 5;

    upstream api {
      server dotnet1:8080;
      server dotnet2:8080;
      server dotnet3:8080;
    }

    server {
      listen 8080;
      server_name localhost;

      location / {
        root /app/index.html; 
      }

      location /api/ {
        proxy_pass http://api/;
      }
    }
}